# Generated by Django 6.0.4 on 2026-06-09 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nomi')),
                ('template_type', models.CharField(choices=[('sertifikat', 'Sertifikat'), ('guvohnoma', 'Guvohnoma')], max_length=20, verbose_name='Turi')),
                ('file', models.FileField(upload_to='templates/', verbose_name='Fayl')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
            ],
            options={
                'verbose_name': 'Hujjat shabloni',
                'verbose_name_plural': 'Hujjat shablonlari',
                'ordering': ['-created_at'],
            },
        ),
    ]
