# Generated by Django 6.0.4 on 2026-06-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Kod')),
                ('name_latin', models.CharField(max_length=255, verbose_name='Lotin (UZ)')),
                ('name_cyrillic', models.CharField(max_length=255, verbose_name='Kirill (UZ)')),
                ('name_russian', models.CharField(max_length=255, verbose_name='Русский')),
                ('name_english', models.CharField(max_length=255, verbose_name='English')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mutaxassislik',
                'verbose_name_plural': 'Mutaxassisliklar',
                'ordering': ['code'],
            },
        ),
    ]
