# Generated by Django 6.0.4 on 2026-06-09 07:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specializations', '0001_initial'),
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=50, verbose_name='Seriya')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Sertifikat raqami')),
                ('employee_name', models.CharField(max_length=255, verbose_name='Xodim F.I.O.')),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Davomiylik (kun)')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
                ('hours', models.PositiveIntegerField(verbose_name='Soat')),
                ('director_name', models.CharField(max_length=255, verbose_name='Direktor F.I.Sh.')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name="Ro'yxatga olish raqami")),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name="Ro'yxatga olish sanasi")),
                ('verification_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Tekshiruv kodi')),
                ('generated_pdf', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='DOCX fayl')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Yaratdi')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='specializations.specialization', verbose_name='Kasb')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='templates_app.documenttemplate', verbose_name='Shablon')),
            ],
            options={
                'verbose_name': 'Sertifikat',
                'verbose_name_plural': 'Sertifikatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
