# Generated by Django 6.0.4 on 2026-06-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='generated_pdf',
            field=models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='PDF fayl'),
        ),
    ]
